# Generated by Django 2.0.5 on 2018-05-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idAluno', models.AutoField(db_column='ID_Aluno', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('foto', models.CharField(blank=True, max_length=11, null=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
                ('Ra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idAtividade', models.AutoField(db_column='ID_Atividade', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.CharField(max_length=999)),
                ('conteudo', models.CharField(blank=True, max_length=999, null=True)),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('extra', models.CharField(blank=True, max_length=999, null=True)),
            ],
            options={
                'db_table': 'Atividade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('idAtividadeVinculada', models.AutoField(db_column='ID_AtividadeVinculada', primary_key=True, serialize=False)),
                ('rotulo', models.CharField(max_length=150)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('dtInicioRespostas', models.DateField(blank=True, db_column='DtInicioRespostas', null=True)),
                ('dtFimRespostas', models.DateField(blank=True, db_column='DtFimRespostas', null=True)),
            ],
            options={
                'db_table': 'AtividadeVinculada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('idCoordenador', models.AutoField(db_column='ID_Coordenador', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
            ],
            options={
                'db_table': 'Coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(db_column='ID_Curso', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.AutoField(db_column='ID_Disciplina', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('planoDeEnsino', models.CharField(blank=True, db_column='PlanodeEnsino', max_length=999, null=True)),
                ('cargaHoraria', models.IntegerField(blank=True, db_column='Cargahoraria', null=True)),
                ('competencias', models.CharField(blank=True, max_length=999, null=True)),
                ('habilidades', models.CharField(blank=True, max_length=999, null=True)),
                ('ementa', models.CharField(blank=True, max_length=999, null=True)),
                ('conteudoProgramatico', models.CharField(blank=True, db_column='ConteudoProgramatico', max_length=999, null=True)),
                ('bibliografiaBasica', models.CharField(blank=True, db_column='BibliografiaBasica', max_length=999, null=True)),
                ('bibliografiaComplementar', models.CharField(blank=True, db_column='BibliografiaComplementar', max_length=999, null=True)),
                ('percentualPratico', models.IntegerField(blank=True, db_column='PercentualPratico', null=True)),
                ('percentualTeorico', models.IntegerField(blank=True, db_column='PercentualTeorico', null=True)),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('idDisciplinaofertada', models.AutoField(db_column='ID_DisciplinaOfertada', primary_key=True, serialize=False)),
                ('dtInicioMatricula', models.DateField(blank=True, db_column='DtInicioMatricula', null=True)),
                ('dtFimMatricula', models.DateField(blank=True, db_column='DtFimMatricula', null=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.CharField(blank=True, max_length=6, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=999, null=True)),
                ('recursos', models.CharField(blank=True, max_length=999, null=True)),
                ('criterioAvaliacao', models.CharField(blank=True, db_column='CriterioAvaliacao', max_length=999, null=True)),
                ('planoDeAulas', models.CharField(blank=True, db_column='PlanoDeAulas', max_length=999, null=True)),
            ],
            options={
                'db_table': 'Disciplinaofertada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('idEntrega', models.AutoField(db_column='ID_Entrega', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('resposta', models.CharField(blank=True, max_length=150, null=True)),
                ('dtEntrega', models.DateField(db_column='DtEntrega')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('dtAvaliacao', models.DateField(db_column='DtAvaliacao')),
                ('obs', models.CharField(blank=True, max_length=999, null=True)),
            ],
            options={
                'db_table': 'Entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('idMensagem', models.AutoField(db_column='ID_Mensagem', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, max_length=999, null=True)),
                ('referencia', models.CharField(blank=True, max_length=999, null=True)),
                ('conteudo', models.CharField(blank=True, max_length=999, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('dtEnvio', models.DateField(blank=True, db_column='DtEnvio', null=True)),
                ('dtResposta', models.DateField(db_column='DtResposta')),
                ('resposta', models.CharField(blank=True, max_length=999, null=True)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idProfessor', models.AutoField(db_column='ID_Professor', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
                ('apelido', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('idSolicitacaoMatricula', models.AutoField(db_column='ID_SolicitacaoMatricula', primary_key=True, serialize=False)),
                ('dtSolicitacao', models.DateField(db_column='DtSolicitacao')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'SolicitacaoMatricula',
                'managed': False,
            },
        ),
    ]
