from .alunos import Aluno 
from .coodernadores import Coordenador
from .disciplinas import Disciplina 
from .disciplinasofertadas import DisciplinaOfertada
from .solicitacoesmatriculas import SolicitacoesMatricula
from .entregas import Entrega
from .mensagens import Mensagem
from .atividadesvinculadas import AtividadeVinculada
from .atividades import Atividade
from .cursos import Curso