# Generated by Django 2.0.5 on 2018-05-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('idAluno', models.AutoField(db_column='ID_Aluno', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('foto', models.CharField(blank=True, max_length=11, null=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
                ('Ra', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Aluno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('idCoordenador', models.AutoField(db_column='ID_Coordenador', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
            ],
            options={
                'db_table': 'Coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('idMensagem', models.AutoField(db_column='ID_Mensagem', primary_key=True, serialize=False)),
                ('assunto', models.CharField(blank=True, max_length=999, null=True)),
                ('referencia', models.CharField(blank=True, max_length=999, null=True)),
                ('conteudo', models.CharField(blank=True, max_length=999, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('dtEnvio', models.DateField(blank=True, db_column='DtEnvio', null=True)),
                ('dtResposta', models.DateField(db_column='DtResposta')),
                ('resposta', models.CharField(blank=True, max_length=999, null=True)),
            ],
            options={
                'db_table': 'Mensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('idProfessor', models.AutoField(db_column='ID_Professor', primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('dtExpiracao', models.DateField(blank=True, db_column='DtExpiracao', null=True)),
                ('apelido', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Professor',
                'managed': False,
            },
        ),
    ]
