# Generated by Django 2.0.5 on 2018-05-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(db_column='ID_Curso', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'Curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('idDisciplina', models.AutoField(db_column='ID_Disciplina', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('planoDeEnsino', models.CharField(blank=True, db_column='PlanodeEnsino', max_length=999, null=True)),
                ('cargaHoraria', models.IntegerField(blank=True, db_column='Cargahoraria', null=True)),
                ('competencias', models.CharField(blank=True, max_length=999, null=True)),
                ('habilidades', models.CharField(blank=True, max_length=999, null=True)),
                ('ementa', models.CharField(blank=True, max_length=999, null=True)),
                ('conteudoProgramatico', models.CharField(blank=True, db_column='ConteudoProgramatico', max_length=999, null=True)),
                ('bibliografiaBasica', models.CharField(blank=True, db_column='BibliografiaBasica', max_length=999, null=True)),
                ('bibliografiaComplementar', models.CharField(blank=True, db_column='BibliografiaComplementar', max_length=999, null=True)),
                ('percentualPratico', models.IntegerField(blank=True, db_column='PercentualPratico', null=True)),
                ('percentualTeorico', models.IntegerField(blank=True, db_column='PercentualTeorico', null=True)),
            ],
            options={
                'db_table': 'Disciplina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('idDisciplinaofertada', models.AutoField(db_column='ID_DisciplinaOfertada', primary_key=True, serialize=False)),
                ('dtInicioMatricula', models.DateField(blank=True, db_column='DtInicioMatricula', null=True)),
                ('dtFimMatricula', models.DateField(blank=True, db_column='DtFimMatricula', null=True)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('turma', models.CharField(blank=True, max_length=6, null=True)),
                ('metodologia', models.CharField(blank=True, max_length=999, null=True)),
                ('recursos', models.CharField(blank=True, max_length=999, null=True)),
                ('criterioAvaliacao', models.CharField(blank=True, db_column='CriterioAvaliacao', max_length=999, null=True)),
                ('planoDeAulas', models.CharField(blank=True, db_column='PlanoDeAulas', max_length=999, null=True)),
            ],
            options={
                'db_table': 'Disciplinaofertada',
                'managed': False,
            },
        ),
    ]
